# Generated by Django 4.1.2 on 2022-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_img',
        ),
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.ImageField(default='default.jpg', upload_to='media/covers'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='media/songs'),
        ),
    ]
